name: Mac Intel Build
on: [push, workflow_dispatch] # This lets you start the build with a button!

jobs:
  build-mac:
    runs-on: macos-13 # This is a Mac computer with an Intel brain
    steps:
      - name: 1. Grab the code
        uses: actions/checkout@v4

      - name: 2. Unzip the secret tools
        run: |
          unzip tools/SDK/sdk.zip -d tools/SDK
          chmod +x tools/Projucer/Projucer.app/Contents/MacOS/Projucer

      - name: 3. Prepare the project
        run: |
          ./tools/Projucer/Projucer.app/Contents/MacOS/Projucer --resave "projects/standalone/HISE Standalone.jucer"

      - name: 4. Build HISE for Intel
        run: |
          cd projects/standalone/Builds/MacOSX
          xcodebuild -project "HISE Standalone.xcodeproj" -configuration Release -arch x86_64

      - name: 5. Save the finished app
        uses: actions/upload-artifact@v4
        with:
          name: HISE-Mac-Intel
          path: projects/standalone/Builds/MacOSX/build/Release/HISE.app
